name: car-dealer-website

services:
  postgresql:
    image: postgres:latest
    shm_size: 64mb
    container_name: "postgresql"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${POSTGRES_TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    networks:
      - car-dealer-website-networks

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "pgadmin"
    depends_on:
      - postgresql
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin4/storage
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - car-dealer-website-networks

  cache:
    image: redis:alpine
    container_name: "cache"
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: >
      sh -c "redis-server /usr/local/etc/redis/redis.conf --requirepass $$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./cache/redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - car-dealer-website-networks

  restful-api:
    image: restful-api:latest
    container_name: "restful-api"
    working_dir: /restful-api
    ports:
      - "8082:8080"
    restart: no
    depends_on:
      - postgresql
      - cache
    volumes:
      - ./logs:/api/logs
    networks:
      car-dealer-website-networks:
        aliases:
          - api

networks:
  car-dealer-website-networks:
    driver: bridge
