spring:
  application:
    name: cardealer
  datasource:
    url: jdbc:postgresql://localhost:5435/car_dealer_db
    username: postgres
    password: Faisal0809
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    lock-retry-count: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080
logging:
  level:
    com.faisal.cardealer: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO